baseURL = "https://i-sanyam.github.io"
languageCode = "en-us"
title = "Sanyam Aggarwal's personal homepage"
paginate = 20

[params]
subtitle = "Living to Learn | Learning to Live"
thumbnail = "thumb.jpeg"

[taxonomies]
   tag = "tags"
   author = "authors"

[menu]
   [[menu.header]]
      identifier = "home"
      name = "Home"
      url = "/"
      weight = 1

   [[menu.header]]
      identifier = "Blogs"
      name = "Blogs"
      url = "/blog"
      weight = 2
