baseURL = "https://develop.sanyamaggarwal.in"
languageCode = "en-us"
title = "Sanyam's Homepage"
subtitle = "Sanyam's Personal Homepage"
paginate = 20
disqusShortname = 'saggarwal'

[params]
subtitle = "Living to Learn | Learning to Live"
thumbnail = "thumb.png"
ogimg = "og-img.jpeg"
googleAnalyticsTagId = "G-QJTB2PMJ2Y"

[taxonomies]
   tag = "tags"
   author = "authors"

[menu]
   [[menu.header]]
      identifier = "home"
      name = "Home"
      url = "/"
      weight = 1

   [[menu.header]]
      identifier = "blogs"
      name = "Blogs"
      url = "/blog"
      weight = 2
   [[menu.header]]
      identifier = "projects"
      name = "Projects"
      url = "/project"
      weight = 3
